// <auto-generated />
using System;
using Javsdt.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Javsdt.Infrastructure.Migrations
{
    [DbContext(typeof(JavsdtContext))]
    partial class JavsdtContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("JavSubtitles", b =>
                {
                    b.Property<int>("JavsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubtitlesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("JavsId", "SubtitlesId");

                    b.HasIndex("SubtitlesId");

                    b.ToTable("JavSubtitles");
                });

            modelBuilder.Entity("Javsdt.Domain.Entitys.Jav", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CDCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Car")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Edition")
                        .HasColumnType("TEXT");

                    b.Property<int>("Error")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ext")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FamilyCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FamilyNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FanartPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasSubtitle")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCracked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDivulged")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeparate")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameWithoutExt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginDir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginNameWithoutExt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Javs");
                });

            modelBuilder.Entity("Javsdt.Domain.Entitys.Subtitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Error")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ext")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameWithoutExt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginDir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginNameWithoutExt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Subtitles");
                });

            modelBuilder.Entity("JavSubtitles", b =>
                {
                    b.HasOne("Javsdt.Domain.Entitys.Jav", null)
                        .WithMany()
                        .HasForeignKey("JavsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Javsdt.Domain.Entitys.Subtitle", null)
                        .WithMany()
                        .HasForeignKey("SubtitlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
