// <auto-generated />
using System;
using Javsdt.Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Javsdt.Data.Migrations.Javsdt
{
    [DbContext(typeof(JavsdtContext))]
    partial class JavsdtContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("JavSubtitles", b =>
                {
                    b.Property<int>("JavsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubtitlesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("JavsId", "SubtitlesId");

                    b.HasIndex("SubtitlesId");

                    b.ToTable("JavSubtitles");
                });

            modelBuilder.Entity("Javsdt.Shared.Entitys.File.Jav", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CDCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Edition")
                        .HasColumnType("TEXT");

                    b.Property<int>("Error")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ext")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FamilyCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FamilyNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FanartPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasSubtitle")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCracked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDivulged")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeparate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JavCarName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameWithoutExt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginDir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginNameWithoutExt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JavCarName");

                    b.ToTable("Javs");
                });

            modelBuilder.Entity("Javsdt.Shared.Models.Entitys.Process.JavCar", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("JavCars");
                });

            modelBuilder.Entity("Javsdt.Shared.Models.Entitys.Process.NasJavFolder", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("CarName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasVideo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Path");

                    b.ToTable("NasJavFolders");
                });

            modelBuilder.Entity("Javsdt.Shared.Models.Entitys.Process.Subtitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Error")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ext")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameWithoutExt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginDir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginNameWithoutExt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Subtitles");
                });

            modelBuilder.Entity("JavSubtitles", b =>
                {
                    b.HasOne("Javsdt.Shared.Entitys.File.Jav", null)
                        .WithMany()
                        .HasForeignKey("JavsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Javsdt.Shared.Models.Entitys.Process.Subtitle", null)
                        .WithMany()
                        .HasForeignKey("SubtitlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Javsdt.Shared.Entitys.File.Jav", b =>
                {
                    b.HasOne("Javsdt.Shared.Models.Entitys.Process.JavCar", null)
                        .WithMany("Javs")
                        .HasForeignKey("JavCarName");
                });

            modelBuilder.Entity("Javsdt.Shared.Models.Entitys.Process.JavCar", b =>
                {
                    b.Navigation("Javs");
                });
#pragma warning restore 612, 618
        }
    }
}
